; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes='print<branch-prob>' -disable-output 2>&1 | FileCheck %s

declare token @llvm.coro.save(ptr)
declare i8 @llvm.coro.suspend(token, i1)
declare void @foo()

; The resume case (0) of a suspend point's dispatch switch in a presplit
; coroutine is overwhelmingly likely: a suspended coroutine is almost always
; resumed exactly once, so code following the suspend point executes (nearly)
; once per entry into the coroutine.


define void @suspend_switch() presplitcoroutine {
; CHECK-LABEL: 'suspend_switch'
; CHECK-NEXT:  ---- Branch Probabilities ----
; CHECK-NEXT:    edge %entry -> %suspend.ret probability is 0x00000800 / 0x80000000 = 0.00%
; CHECK-NEXT:    edge %entry -> %resume probability is 0x7ffff000 / 0x80000000 = 100.00% [HOT edge]
; CHECK-NEXT:    edge %entry -> %destroy probability is 0x00000800 / 0x80000000 = 0.00%
;
entry:
  %save = call token @llvm.coro.save(ptr null)
  %s = call i8 @llvm.coro.suspend(token %save, i1 false)
  switch i8 %s, label %suspend.ret [
    i8 0, label %resume
    i8 1, label %destroy
  ]

resume:
  call void @foo()
  ret void

destroy:
  ret void

suspend.ret:
  ret void
}

; The shared cleanup block dispatching on a constant PHI folds to a known
; destination along each incoming edge; edges arriving from a non-resume case
; of a suspend switch are overwhelmingly unlikely, so the fallthrough
; destination is overwhelmingly likely.


define void @cleanup_dispatch() presplitcoroutine {
; CHECK-LABEL: 'cleanup_dispatch'
; CHECK-NEXT:  ---- Branch Probabilities ----
; CHECK-NEXT:    edge %entry -> %suspend.ret probability is 0x00000800 / 0x80000000 = 0.00%
; CHECK-NEXT:    edge %entry -> %resume probability is 0x7ffff000 / 0x80000000 = 100.00% [HOT edge]
; CHECK-NEXT:    edge %entry -> %cleanup probability is 0x00000800 / 0x80000000 = 0.00%
; CHECK-NEXT:    edge %resume -> %cleanup probability is 0x80000000 / 0x80000000 = 100.00% [HOT edge]
; CHECK-NEXT:    edge %cleanup -> %cleanup.cont probability is 0x7ffff800 / 0x80000000 = 100.00% [HOT edge]
; CHECK-NEXT:    edge %cleanup -> %coro.cleanup probability is 0x00000800 / 0x80000000 = 0.00%
;
entry:
  %save = call token @llvm.coro.save(ptr null)
  %s = call i8 @llvm.coro.suspend(token %save, i1 false)
  switch i8 %s, label %suspend.ret [
    i8 0, label %resume
    i8 1, label %cleanup
  ]

resume:
  call void @foo()
  br label %cleanup

cleanup:
  %dest = phi i32 [ 0, %resume ], [ 2, %entry ]
  %cmp = icmp eq i32 %dest, 0
  br i1 %cmp, label %cleanup.cont, label %coro.cleanup

cleanup.cont:
  ret void

coro.cleanup:
  ret void

suspend.ret:
  ret void
}

; A final suspend cannot be resumed; its resume successor is unreachable.
; The coroutine heuristic must not claim the unreachable successor is likely.


define void @final_suspend() presplitcoroutine {
; CHECK-LABEL: 'final_suspend'
; CHECK-NEXT:  ---- Branch Probabilities ----
; CHECK-NEXT:    edge %entry -> %suspend.ret probability is 0x40000000 / 0x80000000 = 50.00%
; CHECK-NEXT:    edge %entry -> %resume probability is 0x00000000 / 0x80000000 = 0.00%
; CHECK-NEXT:    edge %entry -> %destroy probability is 0x40000000 / 0x80000000 = 50.00%
;
entry:
  %save = call token @llvm.coro.save(ptr null)
  %s = call i8 @llvm.coro.suspend(token %save, i1 true)
  switch i8 %s, label %suspend.ret [
    i8 0, label %resume
    i8 1, label %destroy
  ]

resume:
  unreachable

destroy:
  ret void

suspend.ret:
  ret void
}

; The heuristic only applies to presplit coroutines.


define void @not_a_coroutine() {
; CHECK-LABEL: 'not_a_coroutine'
; CHECK-NEXT:  ---- Branch Probabilities ----
; CHECK-NEXT:    edge %entry -> %suspend.ret probability is 0x2aaaaaab / 0x80000000 = 33.33%
; CHECK-NEXT:    edge %entry -> %resume probability is 0x2aaaaaab / 0x80000000 = 33.33%
; CHECK-NEXT:    edge %entry -> %destroy probability is 0x2aaaaaab / 0x80000000 = 33.33%
;
entry:
  %save = call token @llvm.coro.save(ptr null)
  %s = call i8 @llvm.coro.suspend(token %save, i1 false)
  switch i8 %s, label %suspend.ret [
    i8 0, label %resume
    i8 1, label %destroy
  ]

resume:
  call void @foo()
  ret void

destroy:
  ret void

suspend.ret:
  ret void
}
