; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -S -passes='coro-cleanup' | FileCheck %s

; libstdc++ implements std::noop_coroutine() as a handle to an ordinary global
; frame object (_S_fr) whose resume/destroy slots hold a private empty
; function, rather than via __builtin_coro_noop. The global is writable, so no
; generic pass can fold loads out of it. [coroutine.handle.noop] guarantees
; resume/destroy of the noop coroutine have no observable effects, so calls
; through this handle are elided and phi-merged handles are specialized the
; same way as for llvm.coro.noop().

$_ZNSt7__n486116coroutine_handleINS_22noop_coroutine_promiseEE5_S_frE = comdat any

@_ZNSt7__n486116coroutine_handleINS_22noop_coroutine_promiseEE5_S_frE = linkonce_odr dso_local global { ptr, ptr, [8 x i8] } { ptr @__dummy_resume_destroy, ptr @__dummy_resume_destroy, [8 x i8] undef }, comdat, align 8

declare void @__dummy_resume_destroy()
declare void @effect()
declare void @terminate()

; Symmetric transfer merging a real continuation with the libstdc++ noop
; handle: the noop edge is threaded to a specialized block that simply
; returns.

define void @thread_phi(ptr %frame) {
; CHECK-LABEL: define void @thread_phi(
; CHECK-SAME: ptr [[FRAME:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CONTINUATION:%.*]] = load ptr, ptr [[FRAME]], align 8
; CHECK-NEXT:    [[COND:%.*]] = icmp eq ptr [[CONTINUATION]], null
; CHECK-NEXT:    br i1 [[COND]], label %[[MERGE_NOOP:.*]], label %[[USE_REAL:.*]]
; CHECK:       [[USE_REAL]]:
; CHECK-NEXT:    call void @effect()
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds { ptr, ptr }, ptr [[CONTINUATION]], i32 0, i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-NEXT:    musttail call void [[TMP1]](ptr [[CONTINUATION]])
; CHECK-NEXT:    ret void
; CHECK:       [[MERGE_NOOP]]:
; CHECK-NEXT:    ret void
;
entry:
  %continuation = load ptr, ptr %frame, align 8
  %cond = icmp eq ptr %continuation, null
  br i1 %cond, label %use.noop, label %use.real

use.real:
  call void @effect()
  br label %merge

use.noop:
  br label %merge

merge:
  %handle = phi ptr [ %continuation, %use.real ], [ @_ZNSt7__n486116coroutine_handleINS_22noop_coroutine_promiseEE5_S_frE, %use.noop ]
  %resume = call ptr @llvm.coro.subfn.addr(ptr %handle, i8 0)
  musttail call void %resume(ptr %handle)
  ret void
}

; A direct resume of the libstdc++ noop handle is erased outright.

define void @direct_resume(ptr %frame) {
; CHECK-LABEL: define void @direct_resume(
; CHECK-SAME: ptr [[FRAME:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret void
;
entry:
  %resume = call ptr @llvm.coro.subfn.addr(ptr @_ZNSt7__n486116coroutine_handleINS_22noop_coroutine_promiseEE5_S_frE, i8 0)
  musttail call void %resume(ptr @_ZNSt7__n486116coroutine_handleINS_22noop_coroutine_promiseEE5_S_frE)
  ret void
}

; Destroy through an invoke: the call is erased and control continues at the
; normal destination.

define void @direct_destroy_invoke(ptr %frame) personality i32 0 {
; CHECK-LABEL: define void @direct_destroy_invoke(
; CHECK-SAME: ptr [[FRAME:%.*]]) personality i32 0 {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret void
;
entry:
  %destroy = call ptr @llvm.coro.subfn.addr(ptr @_ZNSt7__n486116coroutine_handleINS_22noop_coroutine_promiseEE5_S_frE, i8 1)
  invoke void %destroy(ptr @_ZNSt7__n486116coroutine_handleINS_22noop_coroutine_promiseEE5_S_frE)
  to label %done unwind label %unwind

done:
  ret void

unwind:
  %pad = landingpad { ptr, i32 }
  catch ptr null
  call void @terminate()
  unreachable
}

; The handle's pointer identity must be preserved: a store of the handle
; (e.g. parking it as a pending continuation) is not rewritten.

define void @keep_store(ptr %p) {
; CHECK-LABEL: define void @keep_store(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store ptr @_ZNSt7__n486116coroutine_handleINS_22noop_coroutine_promiseEE5_S_frE, ptr [[P]], align 8
; CHECK-NEXT:    ret void
;
entry:
  store ptr @_ZNSt7__n486116coroutine_handleINS_22noop_coroutine_promiseEE5_S_frE, ptr %p, align 8
  ret void
}

declare ptr @llvm.coro.subfn.addr(ptr, i8)
