; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -S -passes='module(coro-early),cgscc(coro-split)' | FileCheck %s
; RUN: opt < %s -S -passes='module(coro-early),cgscc(coro-split)' -coro-split-devirt-self-destroy=0 | FileCheck %s --check-prefix=OFF

; A coroutine that destroys its own handle (e.g. from a final awaiter's
; await_suspend, outlined into an await_suspend wrapper whose second parameter
; is the coroutine's frame) does so through the frame's destroy slot. The only
; functions the switch ABI ever stores there are the destroy and cleanup
; clones created by CoroSplit, so the indirect call is speculatively promoted
; to compare-and-branch dispatch over the two clones, with the original
; indirect call as the fallthrough.

define void @f() presplitcoroutine {
; CHECK-LABEL: define void @f() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ID:%.*]] = call token @llvm.coro.id(i32 0, ptr null, ptr @f, ptr @f.resumers)
; CHECK-NEXT:    [[ALLOC:%.*]] = call ptr @malloc(i32 32)
; CHECK-NEXT:    [[HDL:%.*]] = call noalias nonnull ptr @llvm.coro.begin(token [[ID]], ptr [[ALLOC]])
; CHECK-NEXT:    store ptr @f.resume, ptr [[HDL]], align 8
; CHECK-NEXT:    [[DESTROY_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 8
; CHECK-NEXT:    store ptr @f.destroy, ptr [[DESTROY_ADDR]], align 8
; CHECK-NEXT:    br label %[[ALLOCASPILLBB:.*]]
; CHECK:       [[ALLOCASPILLBB]]:
; CHECK-NEXT:    [[AWAITER_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 16
; CHECK-NEXT:    br label %[[POSTSPILL:.*]]
; CHECK:       [[POSTSPILL]]:
; CHECK-NEXT:    br label %[[COROSAVE:.*]]
; CHECK:       [[COROSAVE]]:
; CHECK-NEXT:    [[INDEX_ADDR4:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 24
; CHECK-NEXT:    store i1 false, ptr [[INDEX_ADDR4]], align 1
; CHECK-NEXT:    br label %[[COROSUSPEND:.*]]
; CHECK:       [[COROSUSPEND]]:
; CHECK-NEXT:    br label %[[RESUME_0_LANDING:.*]]
; CHECK:       [[RESUME_0_LANDING]]:
; CHECK-NEXT:    br label %[[AFTERCOROSUSPEND:.*]]
; CHECK:       [[AFTERCOROSUSPEND]]:
; CHECK-NEXT:    switch i8 -1, label %[[RET:.*]] [
; CHECK-NEXT:      i8 0, label %[[COROSAVE1:.*]]
; CHECK-NEXT:      i8 1, label %[[CLEANUP:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[COROSAVE1]]:
; CHECK-NEXT:    store ptr null, ptr [[HDL]], align 8
; CHECK-NEXT:    br label %[[AFTERCOROSAVE:.*]]
; CHECK:       [[AFTERCOROSAVE]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call ptr @f.await_suspend_wrapper(ptr [[AWAITER_RELOAD_ADDR]], ptr [[HDL]])
; CHECK-NEXT:    [[TMP1:%.*]] = call ptr @llvm.coro.subfn.addr(ptr [[TMP0]], i8 0)
; CHECK-NEXT:    call void [[TMP1]](ptr [[TMP0]])
; CHECK-NEXT:    br label %[[COROSUSPEND2:.*]]
; CHECK:       [[COROSUSPEND2]]:
; CHECK-NEXT:    br label %[[RESUME_1_LANDING:.*]]
; CHECK:       [[RESUME_1_LANDING]]:
; CHECK-NEXT:    br label %[[AFTERCOROSUSPEND3:.*]]
; CHECK:       [[AFTERCOROSUSPEND3]]:
; CHECK-NEXT:    switch i8 -1, label %[[RET]] [
; CHECK-NEXT:      i8 0, label %[[STEP1:.*]]
; CHECK-NEXT:      i8 1, label %[[CLEANUP]]
; CHECK-NEXT:    ]
; CHECK:       [[STEP1]]:
; CHECK-NEXT:    br label %[[CLEANUP]]
; CHECK:       [[CLEANUP]]:
; CHECK-NEXT:    [[MEM:%.*]] = call ptr @llvm.coro.free(token [[ID]], ptr [[HDL]])
; CHECK-NEXT:    call void @free(ptr [[MEM]])
; CHECK-NEXT:    br label %[[RET]]
; CHECK:       [[RET]]:
; CHECK-NEXT:    br label %[[COROEND:.*]]
; CHECK:       [[COROEND]]:
; CHECK-NEXT:    br label %[[AFTERCOROEND:.*]]
; CHECK:       [[AFTERCOROEND]]:
; CHECK-NEXT:    ret void
;
; OFF-LABEL: define void @f() {
; OFF-NEXT:  [[ENTRY:.*:]]
; OFF-NEXT:    [[ID:%.*]] = call token @llvm.coro.id(i32 0, ptr null, ptr @f, ptr @f.resumers)
; OFF-NEXT:    [[ALLOC:%.*]] = call ptr @malloc(i32 32)
; OFF-NEXT:    [[HDL:%.*]] = call noalias nonnull ptr @llvm.coro.begin(token [[ID]], ptr [[ALLOC]])
; OFF-NEXT:    store ptr @f.resume, ptr [[HDL]], align 8
; OFF-NEXT:    [[DESTROY_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 8
; OFF-NEXT:    store ptr @f.destroy, ptr [[DESTROY_ADDR]], align 8
; OFF-NEXT:    br label %[[ALLOCASPILLBB:.*]]
; OFF:       [[ALLOCASPILLBB]]:
; OFF-NEXT:    [[AWAITER_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 16
; OFF-NEXT:    br label %[[POSTSPILL:.*]]
; OFF:       [[POSTSPILL]]:
; OFF-NEXT:    br label %[[COROSAVE:.*]]
; OFF:       [[COROSAVE]]:
; OFF-NEXT:    [[INDEX_ADDR4:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 24
; OFF-NEXT:    store i1 false, ptr [[INDEX_ADDR4]], align 1
; OFF-NEXT:    br label %[[COROSUSPEND:.*]]
; OFF:       [[COROSUSPEND]]:
; OFF-NEXT:    br label %[[RESUME_0_LANDING:.*]]
; OFF:       [[RESUME_0_LANDING]]:
; OFF-NEXT:    br label %[[AFTERCOROSUSPEND:.*]]
; OFF:       [[AFTERCOROSUSPEND]]:
; OFF-NEXT:    switch i8 -1, label %[[RET:.*]] [
; OFF-NEXT:      i8 0, label %[[COROSAVE1:.*]]
; OFF-NEXT:      i8 1, label %[[CLEANUP:.*]]
; OFF-NEXT:    ]
; OFF:       [[COROSAVE1]]:
; OFF-NEXT:    store ptr null, ptr [[HDL]], align 8
; OFF-NEXT:    br label %[[AFTERCOROSAVE:.*]]
; OFF:       [[AFTERCOROSAVE]]:
; OFF-NEXT:    [[TMP0:%.*]] = call ptr @f.await_suspend_wrapper(ptr [[AWAITER_RELOAD_ADDR]], ptr [[HDL]])
; OFF-NEXT:    [[TMP1:%.*]] = call ptr @llvm.coro.subfn.addr(ptr [[TMP0]], i8 0)
; OFF-NEXT:    call void [[TMP1]](ptr [[TMP0]])
; OFF-NEXT:    br label %[[COROSUSPEND2:.*]]
; OFF:       [[COROSUSPEND2]]:
; OFF-NEXT:    br label %[[RESUME_1_LANDING:.*]]
; OFF:       [[RESUME_1_LANDING]]:
; OFF-NEXT:    br label %[[AFTERCOROSUSPEND3:.*]]
; OFF:       [[AFTERCOROSUSPEND3]]:
; OFF-NEXT:    switch i8 -1, label %[[RET]] [
; OFF-NEXT:      i8 0, label %[[STEP1:.*]]
; OFF-NEXT:      i8 1, label %[[CLEANUP]]
; OFF-NEXT:    ]
; OFF:       [[STEP1]]:
; OFF-NEXT:    br label %[[CLEANUP]]
; OFF:       [[CLEANUP]]:
; OFF-NEXT:    [[MEM:%.*]] = call ptr @llvm.coro.free(token [[ID]], ptr [[HDL]])
; OFF-NEXT:    call void @free(ptr [[MEM]])
; OFF-NEXT:    br label %[[RET]]
; OFF:       [[RET]]:
; OFF-NEXT:    br label %[[COROEND:.*]]
; OFF:       [[COROEND]]:
; OFF-NEXT:    br label %[[AFTERCOROEND:.*]]
; OFF:       [[AFTERCOROEND]]:
; OFF-NEXT:    ret void
;
entry:
  %awaiter = alloca ptr
  %id = call token @llvm.coro.id(i32 0, ptr null, ptr null, ptr null)
  %size = call i32 @llvm.coro.size.i32()
  %alloc = call ptr @malloc(i32 %size)
  %hdl = call ptr @llvm.coro.begin(token %id, ptr %alloc)
  %suspend.init = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %suspend.init, label %ret [
  i8 0, label %step
  i8 1, label %cleanup
  ]

step:
  %save = call token @llvm.coro.save(ptr null)
  call void @llvm.coro.await.suspend.handle(ptr %awaiter, ptr %hdl, ptr @f.await_suspend_wrapper)
  %suspend = call i8 @llvm.coro.suspend(token %save, i1 true)
  switch i8 %suspend, label %ret [
  i8 0, label %step1
  i8 1, label %cleanup
  ]

step1:
  br label %cleanup

cleanup:
  %mem = call ptr @llvm.coro.free(token %id, ptr %hdl)
  call void @free(ptr %mem)
  br label %ret

ret:
  call void @llvm.coro.end(ptr %hdl, i1 0, token none)
  ret void
}

; Destroys the suspended coroutine (the wrapper's second parameter), then
; transfers to the continuation. The destroy is promoted; the destroy of the
; foreign handle loaded from the awaiter is not.

define ptr @f.await_suspend_wrapper(ptr %awaiter, ptr %hdl) {
; CHECK-LABEL: define ptr @f.await_suspend_wrapper(
; CHECK-SAME: ptr [[AWAITER:%.*]], ptr [[HDL:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CONT:%.*]] = load ptr, ptr [[AWAITER]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = call ptr @llvm.coro.subfn.addr(ptr [[HDL]], i8 1)
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq ptr [[TMP0]], @f.cleanup
; CHECK-NEXT:    br i1 [[TMP1]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_FALSE_ORIG_INDIRECT:.*]]
; CHECK:       [[IF_TRUE_DIRECT_TARG]]:
; CHECK-NEXT:    call void @f.cleanup(ptr [[HDL]]) #[[ATTR5:[0-9]+]]
; CHECK-NEXT:    br label %[[IF_END_ICP:.*]]
; CHECK:       [[IF_FALSE_ORIG_INDIRECT]]:
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq ptr [[TMP0]], @f.destroy
; CHECK-NEXT:    br i1 [[TMP2]], label %[[IF_TRUE_DIRECT_TARG1:.*]], label %[[IF_FALSE_ORIG_INDIRECT2:.*]]
; CHECK:       [[IF_TRUE_DIRECT_TARG1]]:
; CHECK-NEXT:    call void @f.destroy(ptr [[HDL]]) #[[ATTR5]]
; CHECK-NEXT:    br label %[[IF_END_ICP3:.*]]
; CHECK:       [[IF_FALSE_ORIG_INDIRECT2]]:
; CHECK-NEXT:    call void [[TMP0]](ptr [[HDL]]) #[[ATTR5]]
; CHECK-NEXT:    br label %[[IF_END_ICP3]]
; CHECK:       [[IF_END_ICP3]]:
; CHECK-NEXT:    br label %[[IF_END_ICP]]
; CHECK:       [[IF_END_ICP]]:
; CHECK-NEXT:    [[FOREIGN:%.*]] = load ptr, ptr [[CONT]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = call ptr @llvm.coro.subfn.addr(ptr [[FOREIGN]], i8 1)
; CHECK-NEXT:    call void [[TMP3]](ptr [[FOREIGN]])
; CHECK-NEXT:    ret ptr [[CONT]]
;
; OFF-LABEL: define ptr @f.await_suspend_wrapper(
; OFF-SAME: ptr [[AWAITER:%.*]], ptr [[HDL:%.*]]) {
; OFF-NEXT:  [[ENTRY:.*:]]
; OFF-NEXT:    [[CONT:%.*]] = load ptr, ptr [[AWAITER]], align 8
; OFF-NEXT:    [[TMP0:%.*]] = call ptr @llvm.coro.subfn.addr(ptr [[HDL]], i8 1)
; OFF-NEXT:    call void [[TMP0]](ptr [[HDL]])
; OFF-NEXT:    [[FOREIGN:%.*]] = load ptr, ptr [[CONT]], align 8
; OFF-NEXT:    [[TMP1:%.*]] = call ptr @llvm.coro.subfn.addr(ptr [[FOREIGN]], i8 1)
; OFF-NEXT:    call void [[TMP1]](ptr [[FOREIGN]])
; OFF-NEXT:    ret ptr [[CONT]]
;
entry:
  %cont = load ptr, ptr %awaiter, align 8
  call void @llvm.coro.destroy(ptr %hdl)
  %foreign = load ptr, ptr %cont, align 8
  call void @llvm.coro.destroy(ptr %foreign)
  ret ptr %cont
}

declare ptr @llvm.coro.free(token, ptr)
declare i32 @llvm.coro.size.i32()
declare i8  @llvm.coro.suspend(token, i1)
declare void @llvm.coro.resume(ptr)
declare void @llvm.coro.destroy(ptr)

declare token @llvm.coro.id(i32, ptr, ptr, ptr)
declare i1 @llvm.coro.alloc(token)
declare ptr @llvm.coro.begin(token, ptr)
declare void @llvm.coro.await.suspend.handle(ptr, ptr, ptr)
declare void @llvm.coro.end(ptr, i1, token)

declare noalias ptr @malloc(i32)
declare void @free(ptr)
