; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -S -passes='coro-cleanup' | FileCheck %s

; When the store that initializes a coroutine frame's resume/destroy slot is
; visible above the resume/destroy call site (e.g. the frame of a callee
; coroutine was elided into this frame and initialized inline), lowering
; llvm.coro.subfn.addr should forward the stored function instead of emitting
; a load, producing a direct (musttail) call. CoroCleanup creates these loads
; after the last run of GVN, so no later pass can perform this forwarding.

declare void @real_resume(ptr)
declare void @real_destroy(ptr)
declare void @unknown()
declare i64 @readonly_fn() memory(read)

define void @forward_resume(ptr %frame) {
; CHECK-LABEL: define void @forward_resume(
; CHECK-SAME: ptr [[FRAME:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store ptr @real_resume, ptr [[FRAME]], align 8
; CHECK-NEXT:    [[DESTROY_SLOT:%.*]] = getelementptr inbounds nuw i8, ptr [[FRAME]], i64 8
; CHECK-NEXT:    store ptr @real_destroy, ptr [[DESTROY_SLOT]], align 8
; CHECK-NEXT:    [[OTHER_SLOT:%.*]] = getelementptr inbounds nuw i8, ptr [[FRAME]], i64 24
; CHECK-NEXT:    store i64 42, ptr [[OTHER_SLOT]], align 8
; CHECK-NEXT:    [[V:%.*]] = call i64 @readonly_fn()
; CHECK-NEXT:    [[V_SLOT:%.*]] = getelementptr inbounds nuw i8, ptr [[FRAME]], i64 32
; CHECK-NEXT:    store i64 [[V]], ptr [[V_SLOT]], align 8
; CHECK-NEXT:    musttail call void @real_resume(ptr [[FRAME]])
; CHECK-NEXT:    ret void
;
entry:
  store ptr @real_resume, ptr %frame, align 8
  %destroy.slot = getelementptr inbounds nuw i8, ptr %frame, i64 8
  store ptr @real_destroy, ptr %destroy.slot, align 8
  %other.slot = getelementptr inbounds nuw i8, ptr %frame, i64 24
  store i64 42, ptr %other.slot, align 8
  %v = call i64 @readonly_fn()
  %v.slot = getelementptr inbounds nuw i8, ptr %frame, i64 32
  store i64 %v, ptr %v.slot, align 8
  %fn = call ptr @llvm.coro.subfn.addr(ptr %frame, i8 0)
  musttail call void %fn(ptr %frame)
  ret void
}

define void @forward_destroy(ptr %frame) {
; CHECK-LABEL: define void @forward_destroy(
; CHECK-SAME: ptr [[FRAME:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store ptr @real_resume, ptr [[FRAME]], align 8
; CHECK-NEXT:    [[DESTROY_SLOT:%.*]] = getelementptr inbounds nuw i8, ptr [[FRAME]], i64 8
; CHECK-NEXT:    store ptr @real_destroy, ptr [[DESTROY_SLOT]], align 8
; CHECK-NEXT:    call void @real_destroy(ptr [[FRAME]])
; CHECK-NEXT:    ret void
;
entry:
  store ptr @real_resume, ptr %frame, align 8
  %destroy.slot = getelementptr inbounds nuw i8, ptr %frame, i64 8
  store ptr @real_destroy, ptr %destroy.slot, align 8
  %fn = call ptr @llvm.coro.subfn.addr(ptr %frame, i8 1)
  call void %fn(ptr %frame)
  ret void
}

; An intervening call that may write memory could overwrite the slot; the
; load must stay.

define void @no_forward_clobber_call(ptr %frame) {
; CHECK-LABEL: define void @no_forward_clobber_call(
; CHECK-SAME: ptr [[FRAME:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store ptr @real_resume, ptr [[FRAME]], align 8
; CHECK-NEXT:    call void @unknown()
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds { ptr, ptr }, ptr [[FRAME]], i32 0, i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-NEXT:    musttail call void [[TMP1]](ptr [[FRAME]])
; CHECK-NEXT:    ret void
;
entry:
  store ptr @real_resume, ptr %frame, align 8
  call void @unknown()
  %fn = call ptr @llvm.coro.subfn.addr(ptr %frame, i8 0)
  musttail call void %fn(ptr %frame)
  ret void
}

; A store through an unrelated base may alias the slot; the load must stay.

define void @no_forward_unknown_base(ptr %frame) {
; CHECK-LABEL: define void @no_forward_unknown_base(
; CHECK-SAME: ptr [[FRAME:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[OTHER_SLOT:%.*]] = getelementptr inbounds nuw i8, ptr [[FRAME]], i64 16
; CHECK-NEXT:    [[OTHER:%.*]] = load ptr, ptr [[OTHER_SLOT]], align 8
; CHECK-NEXT:    store ptr @real_resume, ptr [[FRAME]], align 8
; CHECK-NEXT:    store i64 0, ptr [[OTHER]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds { ptr, ptr }, ptr [[FRAME]], i32 0, i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-NEXT:    musttail call void [[TMP1]](ptr [[FRAME]])
; CHECK-NEXT:    ret void
;
entry:
  %other.slot = getelementptr inbounds nuw i8, ptr %frame, i64 16
  %other = load ptr, ptr %other.slot, align 8
  store ptr @real_resume, ptr %frame, align 8
  store i64 0, ptr %other, align 8
  %fn = call ptr @llvm.coro.subfn.addr(ptr %frame, i8 0)
  musttail call void %fn(ptr %frame)
  ret void
}

; An overlapping store to the slot with a different type/size intervenes; the
; load must stay.

define void @no_forward_overlap(ptr %frame) {
; CHECK-LABEL: define void @no_forward_overlap(
; CHECK-SAME: ptr [[FRAME:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store ptr @real_resume, ptr [[FRAME]], align 8
; CHECK-NEXT:    store i32 0, ptr [[FRAME]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds { ptr, ptr }, ptr [[FRAME]], i32 0, i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-NEXT:    musttail call void [[TMP1]](ptr [[FRAME]])
; CHECK-NEXT:    ret void
;
entry:
  store ptr @real_resume, ptr %frame, align 8
  store i32 0, ptr %frame, align 8
  %fn = call ptr @llvm.coro.subfn.addr(ptr %frame, i8 0)
  musttail call void %fn(ptr %frame)
  ret void
}

declare ptr @llvm.coro.subfn.addr(ptr, i8)
