; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -S -passes='coro-cleanup' | FileCheck %s

; Symmetric transfer where await_suspend either returns a real continuation or
; the noop coroutine. The noop handle reaches the resume through a phi, so the
; noop-carrying edge must be threaded to a specialized block where the resume
; call is elided; that path should simply return instead of making an indirect
; call to the noop coroutine's empty resume function.

define void @thread_phi(ptr %frame) {
; CHECK-LABEL: define void @thread_phi(
; CHECK-SAME: ptr [[FRAME:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CONTINUATION:%.*]] = load ptr, ptr [[FRAME]], align 8
; CHECK-NEXT:    [[COND:%.*]] = icmp eq ptr [[CONTINUATION]], null
; CHECK-NEXT:    br i1 [[COND]], label %[[MERGE_NOOP:.*]], label %[[USE_REAL:.*]]
; CHECK:       [[USE_REAL]]:
; CHECK-NEXT:    call void @effect()
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds { ptr, ptr }, ptr [[CONTINUATION]], i32 0, i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-NEXT:    musttail call void [[TMP1]](ptr [[CONTINUATION]])
; CHECK-NEXT:    ret void
; CHECK:       [[MERGE_NOOP]]:
; CHECK-NEXT:    ret void
;
entry:
  %continuation = load ptr, ptr %frame, align 8
  %cond = icmp eq ptr %continuation, null
  br i1 %cond, label %use.noop, label %use.real

use.real:
  call void @effect()
  br label %merge

use.noop:
  %noop = call ptr @llvm.coro.noop()
  br label %merge

merge:
  %handle = phi ptr [ %continuation, %use.real ], [ %noop, %use.noop ]
  %resume = call ptr @llvm.coro.subfn.addr(ptr %handle, i8 0)
  musttail call void %resume(ptr %handle)
  ret void
}

; Same, but with the resume function pointer loaded from the frame directly.

define void @thread_phi_load(ptr %frame) {
; CHECK-LABEL: define void @thread_phi_load(
; CHECK-SAME: ptr [[FRAME:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CONTINUATION:%.*]] = load ptr, ptr [[FRAME]], align 8
; CHECK-NEXT:    [[COND:%.*]] = icmp eq ptr [[CONTINUATION]], null
; CHECK-NEXT:    br i1 [[COND]], label %[[MERGE_NOOP:.*]], label %[[USE_REAL:.*]]
; CHECK:       [[USE_REAL]]:
; CHECK-NEXT:    call void @effect()
; CHECK-NEXT:    [[RESUME:%.*]] = load ptr, ptr [[CONTINUATION]], align 8
; CHECK-NEXT:    musttail call void [[RESUME]](ptr [[CONTINUATION]])
; CHECK-NEXT:    ret void
; CHECK:       [[MERGE_NOOP]]:
; CHECK-NEXT:    ret void
;
entry:
  %continuation = load ptr, ptr %frame, align 8
  %cond = icmp eq ptr %continuation, null
  br i1 %cond, label %use.noop, label %use.real

use.real:
  call void @effect()
  br label %merge

use.noop:
  %noop = call ptr @llvm.coro.noop()
  br label %merge

merge:
  %handle = phi ptr [ %continuation, %use.real ], [ %noop, %use.noop ]
  %resume = load ptr, ptr %handle, align 8
  musttail call void %resume(ptr %handle)
  ret void
}

; Destroying a phi-merged handle elides the same way.

define void @thread_phi_destroy(ptr %frame) {
; CHECK-LABEL: define void @thread_phi_destroy(
; CHECK-SAME: ptr [[FRAME:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CONTINUATION:%.*]] = load ptr, ptr [[FRAME]], align 8
; CHECK-NEXT:    [[COND:%.*]] = icmp eq ptr [[CONTINUATION]], null
; CHECK-NEXT:    br i1 [[COND]], label %[[MERGE_NOOP:.*]], label %[[USE_REAL:.*]]
; CHECK:       [[USE_REAL]]:
; CHECK-NEXT:    call void @effect()
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds { ptr, ptr }, ptr [[CONTINUATION]], i32 0, i32 1
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-NEXT:    musttail call void [[TMP1]](ptr [[CONTINUATION]])
; CHECK-NEXT:    ret void
; CHECK:       [[MERGE_NOOP]]:
; CHECK-NEXT:    ret void
;
entry:
  %continuation = load ptr, ptr %frame, align 8
  %cond = icmp eq ptr %continuation, null
  br i1 %cond, label %use.noop, label %use.real

use.real:
  call void @effect()
  br label %merge

use.noop:
  %noop = call ptr @llvm.coro.noop()
  br label %merge

merge:
  %handle = phi ptr [ %continuation, %use.real ], [ %noop, %use.noop ]
  %destroy = call ptr @llvm.coro.subfn.addr(ptr %handle, i8 1)
  musttail call void %destroy(ptr %handle)
  ret void
}

; Negative test: the phi's block does not end in a return, so the edge is not
; threaded and the noop handle lowers to the noop frame constant.

define void @no_thread_non_ret(ptr %frame) {
; CHECK-LABEL: define void @no_thread_non_ret(
; CHECK-SAME: ptr [[FRAME:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[CONTINUATION:%.*]] = load ptr, ptr [[FRAME]], align 8
; CHECK-NEXT:    [[COND:%.*]] = icmp eq ptr [[CONTINUATION]], null
; CHECK-NEXT:    br i1 [[COND]], label %[[MERGE:.*]], label %[[USE_REAL:.*]]
; CHECK:       [[USE_REAL]]:
; CHECK-NEXT:    call void @effect()
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[HANDLE:%.*]] = phi ptr [ [[CONTINUATION]], %[[USE_REAL]] ], [ @NoopCoro.Frame.Const, %[[ENTRY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds { ptr, ptr }, ptr [[HANDLE]], i32 0, i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-NEXT:    call void [[TMP1]](ptr [[HANDLE]])
; CHECK-NEXT:    ret void
;
entry:
  %continuation = load ptr, ptr %frame, align 8
  %cond = icmp eq ptr %continuation, null
  br i1 %cond, label %use.noop, label %use.real

use.real:
  call void @effect()
  br label %merge

use.noop:
  %noop = call ptr @llvm.coro.noop()
  br label %merge

merge:
  %handle = phi ptr [ %continuation, %use.real ], [ %noop, %use.noop ]
  %resume = call ptr @llvm.coro.subfn.addr(ptr %handle, i8 0)
  call void %resume(ptr %handle)
  br label %after

after:
  ret void
}

declare void @effect()
declare ptr @llvm.coro.noop()
declare ptr @llvm.coro.subfn.addr(ptr, i8)
